# Generated by Django 5.1.7 on 2025-05-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Law', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('domain', models.CharField(max_length=255)),
                ('year_experience', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé'), ('indisponible', 'Indisponible')], default='disponible', max_length=50)),
            ],
        ),
    ]
