# Generated by Django 5.1.7 on 2025-05-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Law', '0003_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='first_name',
            field=models.CharField(default='fist-name', max_length=128),
        ),
    ]
