# Generated by Django 5.1.7 on 2025-05-31 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Law', '0005_remove_lawyer_domain_lawyer_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyer',
            old_name='profession',
            new_name='domain',
        ),
    ]
